# Generated by Django 4.2.10 on 2026-02-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_short_urls_user_usercreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_urls',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='UserCreation',
        ),
    ]
